# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EntityMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='jurnalo.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passed_at', models.DateTimeField()),
                ('hash', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=8)),
                ('protected', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='jurnalo.Entity')),
                ('on_behalf_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jurnalo.Entity')),
                ('previous_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_record', to='jurnalo.Record')),
                ('related_to', models.ManyToManyField(related_name='related_records', to='jurnalo.Record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='jurnalo.Record')),
            ],
        ),
    ]
