# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnalo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='uid',
            new_name='urn',
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
