# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnalo', '0002_auto_20170905_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='info_url',
            field=models.URLField(null=True),
        ),
    ]
